const introducao = '<div class="alinha-body"><img src="imagens/ola.jpg" alt="" class="imagem-size"><p class="alinha-texto">Olá! amado jogador, tudo bem? Sou só mais um habitante do planeta YUTU, e a partir de agora você também faz parte desse planeta. Bom seu nome é Hank, explicarei o que aconteceu com nosso planeta, YUTU é um planeta popularizado por humanos ele fica fora da nossa galáxia. Porém os recursos naturais daqui estão ficando escassos e precisamos pesquisar se à terra está pronta para nos receber novamente. E você foi enviado para esta missão, mas não temos nenhuma resposta sua a 3 anos e vale lembrar que você é um robô humanoide.... Não se esqueça jogador este jogo é de tomada de decisões então só cabe a você decidir o futuro do nosso planeta.</p><div> <button onclick="carregarConteudo(conteudoA)">Vou fazer cagada, to vendo já</button> <button onclick="carregarConteudo(conteudoA)">Ok, vamos nessa</button></div> </div>'

const conteudoA = '<div class="alinha-body"><img src="imagens/conteudoA(amanhacer).jpg" alt="" class="imagem-size"><p class="alinha-texto">Sinto uma luz incomodando meus sensores que ficam nas regiões dos olhos, aparentemente está amanhecendo, ligeiramente penso: - vou olhar meu visor de bateria. Percebo que minha bateria está acabando, sinto que estou com alguns vazamentos, aos poucos minha visão vai ficando mais nítida, e consigo notar aquela paisagem que até para mim que não tenho sentimentos consigo me sentir feliz e em paz. Chego até a pensar: -Desligar eternamente aqui não seria tão ruim.</p><div> <button onclick="carregarConteudo(conteudoB1)">Esperar o sistema parar totalmente</button> <button onclick="carregarConteudo(conteudoB2)">Escolher reagir</button></div> </div>';

const conteudoB1 = '<div class="alinha-body"><img src="imagens/ConteudoB1(morte).jpg" alt="" class="imagem-size"><p class="alinha-texto">Gradualmente sinto meus sensores das pernas parando, começo a sentir minhas articulações travarem, consigo observar algumas faíscas saindo e enfim meus sensores de visão ficam escuros e por fim penso: -É, este é o fim. Envio minha mensagem final para meu planeta YUTU e desligo eternamente.</p><div><button onclick="reiniciar()">Reiniciar</button></div>';

const conteudoB2 = '<div class="alinha-body"><img src="imagens/OpcaoB2(cidadedestruida).jpeg" alt="" class="imagem-size"><p class="alinha-texto">Escuto algo como se fosse uma voz dentro da minha cabeça dizendo que ainda não era hora, tento me levantar, mas não consigo, tento novamente e apoiado em uma arvore. E começo a andar me arrastando, sinto saindo cada vez mais fluido saindo de dentro de mim, minha bateria entrando em modo de economia, mas após andar alguns minutos consigo ver de longe algo que parecia um prédio, era um lugar muito familiar a YUTU, só que muito mais destruído. E vou entrando mais e mais até que vejo algo parecido a mim chego mais próximo do objeto e percebo que é uma caixa com peças minhas, inclusive um carregador, mangueiras e mais fluido.Fico pensando se uso elas ou se procuro em outros lugares.</p><div> <button onclick="carregarConteudo(conteudoC1)">Sim, procura.</button> <button onclick="carregarConteudo(conteudoC2)">Não, usa estas mesmas.</button></div> </div>';

const conteudoC1 = '<div class="alinha-body"><img src="imagens/CidadePorDentro(C1eC2).png" alt="" class="imagem-size"><p class="alinha-texto">Quando resolvo sair daquele lugar e procurar peças que eu estava, novamente escuto a voz me dizendo oque fazer dessa vez a voz dizia: -Pega só pegar a coloquei aí, justamente para ti. Então resolvo fazer meus reparos.</p><div> <button onclick="carregarConteudo(conteudoD)">Recarrego minha bateria primeiro e depois faço meus reparos.</button> <button onclick="carregarConteudo(conteudoD)">Começo a fazer imediatamente os reparos e depois me carrego.</button></div> </div>';

const conteudoC2 = '<div class="alinha-body"><img src="imagens/CidadePorDentro(C1eC2).png" alt="" class="imagem-size"><p class="alinha-texto">Espero um pouco mas fico em dúvida em que mexer primeiro.</p><div>  <button onclick="carregarConteudo(conteudoD)">Recarrego minha bateria primeiro e depois faço meus reparos.</button> <button onclick="carregarConteudo(conteudoD)">Começo a fazer imediatamente os reparos e depois me carrego.</button></div> </div>';


const conteudoD = '<div class="alinha-body"><img src="imagens/Contedo(D).jpg" alt="" class="imagem-size"><p class="alinha-texto">Agora estou carregado e sem vazamentos. Me sinto um robô novo, mas aquela voz estranha está me incomodando, me pergunto: -Será que é alguém de YUNTO tentando se comunicar comigo? Mas resolvo ir andando pela cidade vendo aqueles prédios enormes, olho meu sensor de oxigênio e vejo que ele está apontando um bom índice. Imediatamente penso em enviar o relatório para meus superiores Mas consigo observar um movimento em um lugar distante. Coisa pequena e rápida</p><div><button onclick="carregarConteudo(conteudoE2)">Ir ver oque era aquilo</button> <button onclick="carregarConteudo(conteudoE1)">Enviar o relatório.</button></div> </div>';

const conteudoE1 = '<div class="alinha-body"><img src="imagens/Predio(ConteudoE1).jpg" alt="" class="imagem-size"><p class="alinha-texto">Envio o relatório mostrando todos os dados que consegui adquirir nesse planeta. E vou para cima de um prédio esperar resposta e retirada desse local. Afinal já fazia anos que tinha saído de YUNTO.</p><button onclick="reiniciar()">Reiniciar</button>';

const conteudoE2 = '<div class="alinha-body"><img src="imagens/Predio(ConteudoE1).jpg" alt="" class="imagem-size"><p class="alinha-texto">Rapidamente começo a correr em direção ao local que vi aquele movimento e novamente vejo mais um movimento, começo a correr como se chegar até aquele local fosse minha motivação de vida. Quando chego perto posso observar um animal pequeno, que tremia e parecia ter muita raiva de mim. Utilizei meu scan para descobrir que animal era aquele. Após analisar descubro que era um gato e vejo também que eles são animais dóceis e amáveis. Nesse momento me pergunto se devo pega-lo ou não</p><div><button onclick="carregarConteudo(conteudoF1)">Deixa-lo</button> <button onclick="carregarConteudo(conteudoF2)">Pega-lo</button></div> </div>';

const conteudoF1 = '<div class="alinha-body"><img src="imagens/lilly.jpg" alt="" class="imagem-size"><p class="alinha-texto">Resolvo deixar e olhar para trás quando vi pessoas, SIM PESSOAS achei aquilo muito estranho nunca pensei que iria ver pessoas alguma vez na vida. Porem percebo que eles sentem muito medo de mim enfim resolvo me comunicar com eles e DIGO:-Olá eu me chamo Hank,  e venho de YUNTO um planeta fora dessa galáxia.Quando uma criança que gritava seu nome que era Lilly falava bem alto:-Nós sabemos de onde você vem o monstro é desse mesmo mundo não queremos outra coisa, seja la oque você for, nos controlando .Por um minuto não fazia ideia do que ela dizia, então precisava tentar descobrir oque estava acontecendo.</p><div><button onclick="carregarConteudo(conteudoF11)">Usar scan para ver memorias da garota</button> <button onclick="carregarConteudo(conteudoF12)">Perguntar oque estava acontecendo</button></div> </div>';

const conteudoF2 = '<div class="alinha-body"><img src="imagens/morte.jpg" alt="" class="imagem-size"><p class="alinha-texto">Quando chego próximo para pega-lo sinto uma enorme pancada na região da minha cabeça e no mesmo momento meus sensores começaram a entrar em curto então começo a sentir aquela sensação de fosse desligar eternamente e sim isso aconteceu, não sei oque me atingiu, não sei o porque mas esse foi o fim que o Nome jogador levou.</p><button onclick="reiniciar()">Reiniciar</button></div>';

const conteudoF11 = '<div class="alinha-body"><img src="imagens/lilly.jpg" alt="" class="imagem-size"><p class="alinha-texto">Resolvo deixar e olhar para trás quando vi pessoas, SIM PESSOAS achei aquilo muito estranho nunca pensei que iria ver pessoas alguma vez na vida. Porem percebo que eles sentem muito medo de mim enfim resolvo me comunicar com eles e DIGO:-Olá eu me chamo Hank,  e venho de YUNTO um planeta fora dessa galáxia.Quando uma criança que gritava seu nome que era Lilly falava bem alto:-Nós sabemos de onde você vem o monstro é desse mesmo mundo não queremos outra coisa, seja la oque você for, nos controlando .Por um minuto não fazia ideia do que ela dizia, então precisava tentar descobrir oque estava acontecendo.</p><div><button onclick="carregarConteudo(conteudoG)">Agora tudo faz sentido?</button> <button onclick="carregarConteudo(conteudoG)">Isso é possível?</button></div> </div>';

const conteudoF12 = '<div class="alinha-body"><img src="imagens/lilly.jpg" alt="" class="imagem-size"><p class="alinha-texto">Rapidamente perguntei:-Mas oque eu e o povo fizeram a vocês?Lilly me olha e reponde:- O monstro era um humanoide igual a você, um modelo mais antigo, mas ainda sim igual você, provavelmente vindo de YUNTO. Provavelmente vocês tenham a mesma missão, porém ele, o monstro, acabou tomado pelo poder e graças a uma falha em seu sistema começou a gostar daquela sensação e assim começou a destruir cidades, matar pessoas, fazer com que os humanos fossem obrigados a se esconder e hoje o monstro é o dono da cidade, do país e desse mundo.</p><div><button onclick="carregarConteudo(conteudoG)">Agora tudo faz sentido?</button> <button onclick="carregarConteudo(conteudoG)">Isso é possível?</button></div> </div>';

const conteudoG = '<div class="alinha-body"><img src="imagens/pensamento.jpg" alt="" class="imagem-size"><p class="alinha-texto">Minha Unidade Central não conseguia processar essa informação fazia cálculos e mais cálculos para saber se era possível algo desse nível acontecer. Mas eu conseguia processar esses sentimentos afinal também tenho a mesma falha que o monstro, então pergunto a Lilly:-O-onde eu consigo encontrar O mostro?Lilly da uma risada e responde:-O monstro está dentro da minha, da sua e da nossa cabeça. Ele já sabe que você está aqui e sabe que quer ir atrás dele. Mas cuidado todos que foram acabaram não voltando.Uma sensação estranha me tomou, era algo frio, algo semelhante ao desligamento acho que o nome disso é medo.</p><div><button onclick="carregarConteudo(conteudoH2)">Ficar com a Lilly e o resto dos humanos</button> <button onclick="carregarConteudo(conteudoH1)">Ir atrás do Monstro</button></div> </div>';

const conteudoH2 = '<div class="alinha-body"><img src="imagens/Explosão.jpg" alt="" class="imagem-size"><p class="alinha-texto">Lilly vou esperar ele vir até nós para poder conversar com ele. 3 dias se passaram quando como de uma forma quase magica aparece uma luz muito forte no céu, todos humanos sabiam oque era, muitos choravam outros pediam algo para um ser chamadoDeus. Quando aquele clarão chegou no chão parecia água, limpando tudo e todos que estavam no caminho.<button onclick="reiniciar()">Reiniciar</button></div>';

const conteudoH1 = '<div class="alinha-body"><img src="imagens/imgorre.jpg" alt="" class="imagem-size"><p class="alinha-texto">Mesmo com aquela sensação ruim decido ir atrás do Monstro, pergunta a Lilly: -Lilly você sabe o lugar em que ele fica?Lilly me olha com uma cara de medo e responde:-Ele fica na torre mais alta da cidade.Então eu me recarrego e parto para a busca, andei algumas horas seguindo as instruções que a Lilly tinha me passado. Até que eu cheguei lá, era uma torre diferente. Sombria que só de estar perto minha unidade de processamento começava a ter mais falhas. Então vejo ele lá em cima o Monstro, um humanoide de beleza única e com partes de muitos outros humanoides e até de humanos, fiquei me perguntando se eu iria subir ou não </p><div><button onclick="carregarConteudo(conteudoJ)">Subir por conta própria</button> <button onclick="Esperar aqui!(conteudoH11)">Ir atrás do Monstro</button></div> </div>';

const conteudoH11 = '<div class="alinha-body"><img src="imagens/imgorre.jpg" alt="" class="imagem-size"><p class="alinha-texto">Resolvo esperar aqui mesmo, porém após aproximadamente 5 minutos vejo algo se dirigindo até mim, não era O Monstro era um amontoado de partes que chegou em mim e disse:-Eu sei oque você está sentindo isso é normal venha.Enquanto andávamos aquele amontoado me disse novamente:-O nome disso que você sente é medo.Começamos a subir a sombria torre.  </p><div><button onclick="carregarConteudo(conteudoJ)">Você não tem opção apenas continue</button></div> </div>';

const conteudoJ = '<div class="alinha-body"><img src="imagens/Painsentado.gif" alt="" class="imagem-size"><p class="alinha-texto">Quando cheguei o Monstro me disse:-Primeiro de tudo Boa noite, essa cidade é tão escura que nem sei o horário, eu me chamo Pain e você como se chama?Olhei para ele, aquele cabelo laranja aquelas roupas pretas e vermelhas e disse:- Eu me chamo Hank!!!Pain estava sentado em algo que parecia uma língua bem na beira da torre ele olha e chama para ir até lá </p><div><button onclick="carregarConteudo(conteudoL)">Ir proxima ao Pain</button></div>';

const conteudoL = '<div class="alinha-body"><img src="imagens/Painsentado.gif" alt="" class="imagem-size"><p class="alinha-texto">Mesmo com aquela sensação ruim decido ir atrás do Monstro, pergunta a Lilly: -Lilly você sabe o lugar em que ele fica?Lilly me olha com uma cara de medo e responde:-Ele fica na torre mais alta da cidade.Então eu me recarrego e parto para a busca, andei algumas horas seguindo as instruções que a Lilly tinha me passado. Até que eu cheguei lá, era uma torre diferente. Sombria que só de estar perto minha unidade de processamento começava a ter mais falhas. Então vejo ele lá em cima o Monstro, um humanoide de beleza única e com partes de muitos outros humanoides e até de humanos, fiquei me perguntando se eu iria subir ou não </p><div><button onclick="carregarConteudo(conteudoM1)">Aceitar</button> <button onclick="Esperar aqui!(conteudoM2)">Recusaar!</button></div> </div>'

const conteudoM1 = '<div class="alinha-body"><img src="imagens/imgorre.jpg" alt="" class="imagem-size"><p class="alinha-texto">Após eu aceitar Pain me olha e diz, está vendo aquele canhão? Atire com ele naquele prédio e prove sua lealdade a mim, me aproximei do canhão e pensei em desistir, quando Pain coloca algo em minha cabeça e diz:- Lembra daquela voz que te salvou? Era eu, então me retribua e mate-os.Após aquela frase não conseguia mais controlar meu corpo e só consegui ouvir uma voz falando agora você é meu e após isso vi uma forte luz e o prédio caindo. </p><button onclick="reiniciar()">Reiniciar</button></div>';

const conteudoM2 = '<div class="alinha-body"><img src="imagens/Explosão.jpg" alt="" class="imagem-size"><p class="alinha-texto">Quando eu recusei Pain tentou me atingir com uma espada, que rapidamente tinha sido trocada de lugar com o seu braço, nesse momento já estava enviando um relatório para YUNTO caso fosse desligado eles saberiam o que aconteceu, quando Pain tentou me atingir novamente ele conseguiu destruir meu braço direito, justamente qual a voz tinha me ajuda a arrumar e naquele momento eu entendi o que era sentir dor, mas já era tarde. Eu estava perdendo muito fluido e sem perceber ele conseguiu perfurar minhas mangueiras da barriga, no mesmo momento cai e senti minhas pernas parando. Enquanto isso Pain começava a se gabar dizendo que era o humanoide mais poderoso do planeta e que era inevitável. Nesse momento percebo que estou ao lado de um canhão, assim que Pain virou as costas me conectei ao canhão e destruí eu, o canhão a torre e o mais importante eu destruí o Pain.</p><div><button onclick="Esperar aqui!(conteudoFim)">FIM</button></div> </div>';

const conteudoFinal = '<div class="alinha-body"><img src="imagens/Nave.jpg" alt="" class="imagem-size"><p class="alinha-texto">O final ainda não chegou caro jogador, esta história precisa de muita explicação, como por exemplo oque aconteceu com a Lilly, e o Hank, Mas fiquem tranquilos conseguimos recuperar a memoria dele e sim o Hank  vai voltar, mas será que ele fez a coisa correta?</div>'

var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo){
    elemento.innerHTML = conteudo;
}

function darkMode()  {
    var element = document.body;
    element.classList.toggle("dark-mode-body");
}

function reiniciar() {
    carregarConteudo(introducao);
}

carregarConteudo(introducao)